// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: watch_GUI

#include "ui.h"

// COMPONENT uiLabelTime

lv_obj_t * ui_uiLabelTime_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_uiLabelTime;
    cui_uiLabelTime = lv_label_create(comp_parent);
    lv_obj_set_width(cui_uiLabelTime, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(cui_uiLabelTime, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(cui_uiLabelTime, 0);
    lv_obj_set_y(cui_uiLabelTime, -30);
    lv_obj_set_align(cui_uiLabelTime, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(cui_uiLabelTime, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_opa(cui_uiLabelTime, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_text_font(cui_uiLabelTime, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_EDITED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_UILABELTIME_NUM);
    children[UI_COMP_UILABELTIME_UILABELTIME] = cui_uiLabelTime;
    lv_obj_add_event_cb(cui_uiLabelTime, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_uiLabelTime, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_uiLabelTime_create_hook(cui_uiLabelTime);
    return cui_uiLabelTime;
}

