// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: watch_GUI

#include "ui.h"

lv_obj_t * uic_uiLabelAlert;
lv_obj_t * uic_uiPanelAlert;
lv_obj_t * uic_uiLabelDate;
lv_obj_t * uic_uiLabelTime;
lv_obj_t * uic_arcAlert;
lv_obj_t * uic_arcSafe;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_arcSafe = NULL;
lv_obj_t * ui_arcSafe1 = NULL;
lv_obj_t * ui_arcAlert = NULL;
lv_obj_t * ui_uiLabelTime = NULL;
lv_obj_t * ui_uiLabelDate = NULL;
lv_obj_t * ui_uiPanelAlert = NULL;
lv_obj_t * ui_uiLabelAlert = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_arcSafe = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_arcSafe, 240);
    lv_obj_set_height(ui_arcSafe, 240);
    lv_obj_set_align(ui_arcSafe, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_arcSafe, 100);
    lv_arc_set_bg_angles(ui_arcSafe, 0, 360);
    lv_arc_set_rotation(ui_arcSafe, 90);
    lv_obj_set_style_arc_color(ui_arcSafe, lv_color_hex(0x44DDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcSafe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcSafe, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_arcSafe, lv_color_hex(0x00FFF4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_arcSafe, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_arcSafe, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_arcSafe, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arcSafe, lv_color_hex(0x25E3F1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcSafe, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcSafe, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arcSafe, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_arcSafe, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_arcSafe, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcSafe, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_arcSafe, LV_BORDER_SIDE_NONE, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_arcSafe, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_arcSafe, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_arcSafe, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_arcSafe, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_arcSafe, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_arcSafe1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_arcSafe1, 240);
    lv_obj_set_height(ui_arcSafe1, 240);
    lv_obj_set_align(ui_arcSafe1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_arcSafe1, 100);
    lv_arc_set_bg_angles(ui_arcSafe1, 0, 360);
    lv_arc_set_rotation(ui_arcSafe1, 90);
    lv_obj_set_style_arc_color(ui_arcSafe1, lv_color_hex(0x44DDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcSafe1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcSafe1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_arcSafe1, lv_color_hex(0x00FFF4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_arcSafe1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_arcSafe1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_arcSafe1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arcSafe1, lv_color_hex(0x1DFC04), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcSafe1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcSafe1, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arcSafe1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_arcSafe1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_arcSafe1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcSafe1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_arcSafe1, LV_BORDER_SIDE_NONE, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_arcSafe1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_arcSafe1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_arcSafe1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_arcSafe1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_arcSafe1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_arcAlert = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_arcAlert, 240);
    lv_obj_set_height(ui_arcAlert, 240);
    lv_obj_set_align(ui_arcAlert, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arcAlert, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_value(ui_arcAlert, 100);
    lv_arc_set_bg_angles(ui_arcAlert, 0, 360);
    lv_arc_set_rotation(ui_arcAlert, 90);

    lv_obj_set_style_shadow_color(ui_arcAlert, lv_color_hex(0xC40B12), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_arcAlert, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_arcAlert, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_arcAlert, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arcAlert, lv_color_hex(0xC40B12), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcAlert, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcAlert, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arcAlert, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_uiLabelTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLabelTime, 145);
    lv_obj_set_height(ui_uiLabelTime, 48);
    lv_obj_set_x(ui_uiLabelTime, 0);
    lv_obj_set_y(ui_uiLabelTime, -15);
    lv_obj_set_align(ui_uiLabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelTime, "h:m");
    lv_obj_set_style_text_color(ui_uiLabelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_uiLabelTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_uiLabelTime, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelTime, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelDate = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiLabelDate, 110);
    lv_obj_set_height(ui_uiLabelDate, 27);
    lv_obj_set_x(ui_uiLabelDate, -6);
    lv_obj_set_y(ui_uiLabelDate, 30);
    lv_obj_set_align(ui_uiLabelDate, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_uiLabelDate, "$$$, dd mmm");
    lv_obj_set_style_text_color(ui_uiLabelDate, lv_color_hex(0xD2FFFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_uiLabelDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelDate, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiPanelAlert = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiPanelAlert, 130);
    lv_obj_set_height(ui_uiPanelAlert, 30);
    lv_obj_set_x(ui_uiPanelAlert, 0);
    lv_obj_set_y(ui_uiPanelAlert, 60);
    lv_obj_set_align(ui_uiPanelAlert, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiPanelAlert, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiPanelAlert, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiPanelAlert, lv_color_hex(0x1A1A24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPanelAlert, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPanelAlert, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_uiPanelAlert, lv_color_hex(0xD33535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiPanelAlert, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_uiPanelAlert, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiPanelAlert, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelAlert = lv_label_create(ui_uiPanelAlert);
    lv_obj_set_width(ui_uiLabelAlert, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelAlert, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uiLabelAlert, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelAlert, "SAFE");
    lv_obj_set_style_text_color(ui_uiLabelAlert, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelAlert, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelAlert, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_arcSafe = ui_arcSafe;
    uic_arcAlert = ui_arcAlert;
    uic_uiLabelTime = ui_uiLabelTime;
    uic_uiLabelDate = ui_uiLabelDate;
    uic_uiPanelAlert = ui_uiPanelAlert;
    uic_uiLabelAlert = ui_uiLabelAlert;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_arcSafe = NULL;
    ui_arcSafe = NULL;
    ui_arcSafe1 = NULL;
    uic_arcAlert = NULL;
    ui_arcAlert = NULL;
    uic_uiLabelTime = NULL;
    ui_uiLabelTime = NULL;
    uic_uiLabelDate = NULL;
    ui_uiLabelDate = NULL;
    uic_uiPanelAlert = NULL;
    ui_uiPanelAlert = NULL;
    uic_uiLabelAlert = NULL;
    ui_uiLabelAlert = NULL;

}
