// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: watch_GUI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_arcSafe;
extern lv_obj_t * ui_arcSafe1;
extern lv_obj_t * ui_arcAlert;
extern lv_obj_t * ui_uiLabelTime;
extern lv_obj_t * ui_uiLabelDate;
extern lv_obj_t * ui_uiPanelAlert;
extern lv_obj_t * ui_uiLabelAlert;
// CUSTOM VARIABLES
extern lv_obj_t * uic_arcSafe;
extern lv_obj_t * uic_arcAlert;
extern lv_obj_t * uic_uiLabelTime;
extern lv_obj_t * uic_uiLabelDate;
extern lv_obj_t * uic_uiPanelAlert;
extern lv_obj_t * uic_uiLabelAlert;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

