; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

lib_archive = no
lib_ldf_mode = deep+

; Chỉ gọi các thư viện thực sự phụ thuộc từ bên ngoài
lib_deps =
    SparkFun LSM6DS3 Breakout@^1.0.0
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3
    lovyan03/LovyanGFX@^1.1.12
    lvgl/lvgl@^8.3.11
    arduino-libraries/ArduinoBLE@^1.3.6
    
; Định nghĩa tham số build
build_flags =
    -I lib/deploy
    -I lib/deploy/model-parameters
    -I lib/deploy/tflite-model
    
    ; --- CẤU HÌNH BẬT OPI PSRAM CHO ESP32-S3 ---
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D CORE_DEBUG_LEVEL=0
    
    ; --- EDGE IMPULSE CONFIG ---
    -D EI_PORTING_ARDUINO=0
    -D EI_PORTING_ESPRESSIF=1
    -O3
    -Wl,--gc-sections

    ; --- LVGL CONFIG ---
    -D LV_CONF_SKIP
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_COLOR_DEPTH=16
    -D LV_COLOR_16_SWAP=1          ; <=== Thêm dòng này để fix lỗi swap
    -D LV_FONT_MONTSERRAT_20=1     ; <=== Thêm dòng này khai báo font 20
    -D LV_FONT_MONTSERRAT_48=1     ; <=== Thêm dòng này khai báo font 48
    -D LV_TICK_CUSTOM=1
    -I src/ui

; Thêm tham số định nghĩa OPI PSRAM cho bo mạch
board_build.arduino.memory_type = qio_opi

; Bắt PlatformIO biên dịch toàn bộ mã nguồn bên trong lib/deploy
build_src_filter = +<*> -<.git/> -<.pio/> -<build/> -<.venv/> +<../lib/deploy/> -<../lib/deploy/source/>